### ISSUE TITLE
Port 7071 Held open after debugging v2 Functions

### ISSUE THREAD

**Issue by joescars** [Azure/Azure-Functions#1000]
My setup
Windows 10 Enterprise (MSFT Corp Image)
Visual Studio 15.8.7
Azure Functions and Web Jobs Tools   15.9.02046.0

**Issue**
After debugging a **v2** function, closing the window and trying to debug again results in the following error 90% of the time. 

**Port 7071 is unavailable. Close the process using that port, or specify another port using --port [-p].**
_Press any to continue...._

The only resolution is to restart Visual Studio. 

Example Code that will repro the error for me consistently 

```c#
[FunctionName("GetRating")]
public static async Task<IActionResult> Run(
	[HttpTrigger(AuthorizationLevel.Function, "get", Route = "GetRating/{ratingId}")] HttpRequest req,
	[CosmosDB(
		databaseName: "serverlessoh",
		collectionName: "ratings",
		ConnectionStringSetting = "myCosmosDB",
		PartitionKey = "{ratingId}",
		Id = "{ratingId}")]ProductRating rating,
	ILogger log)
{
	log.LogInformation("GetRating triggered");

	return rating != null
		? (ActionResult)new OkObjectResult(rating)
		: new NotFoundObjectResult("Please pass a valid ratingId");
}
```

**Comment by JohnReeson** [comment]
Same issue [here] and [fix](https://github.com/Azure/azure-functions-core-tools/commit/b34b693ff6b031dffeb68fb01f6bdb47d963e18f) has been committed. Just wait for next release.

**Comment by JohnReeson** [comment]
Confirm it's fixed in cli `2.1.746` on my side. 
```
Azure Functions Core Tools (2.1.746 Commit hash: 6519c63d9ca5ad86ef33236569fd2813c9c350ba)
Function Runtime Version: 2.0.12134.0

**Comment by smadhukar2000** [comment]
Hi,
This issue still occurring as on 3.Apr.2020.
Did somehow this issue reopened ?

VS2019, Windows 10, Function v2.0.

I have to restart machine to release the port as of now.

Thanks,

**Comment by joescars** [comment]
@smadhukar2000 - I have not had this issue for quite a while. I will suggest opening a new issue with your setup and repro steps. You can reference this original issue.
