### ISSUE TITLE
Publish failed: Web Deploy cannot modify the file...

### ISSUE THREAD

**Issue by denyss-digiterre** [Azure/Azure-Functions#1003]
![image](https://user-images.githubusercontent.com/29480181/47441827-f504a500-d7a8-11e8-95af-112480178b13.png)

C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web deployment task failed. (Web Deploy cannot modify the file '....dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.) [C:\ ... .csproj]
  Publish failed to deploy.

**Comment by JohnReeson** [comment]
@denyss-digiterre  The link in your error message should solve the problem. 

Add `<EnableMSDeployAppOffline>true</EnableMSDeployAppOffline>` in your publish profile(.pubxml). This setting take the app offline so the file lock is released and your app will start automatically after deploy.

**Comment by avjabalpur** [comment]
I have added this setting, but still getting the same issue 
C:\Program Files\dotnet\sdk\2.1.504\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): Error : Web deployment task failed. (Web Deploy cannot modify the file 'hostfxr.dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.)

**Comment by chmarti** [comment]
This is also still happening to me with Function Apps. Even after I have added <EnableMSDeployAppOffline>true</EnableMSDeployAppOffline> to the publish profile and the App is completely stopped. Why was this issue closed??? The internet is full of others having this problem.

**Comment by kiran290** [comment]
I have added this setting, but still getting the same issue, can anyone help me with this.

 
![image](https://user-images.githubusercontent.com/59478011/71727656-02afc300-2e61-11ea-8694-bd784fd89e2e.png)

Thanks!

**Comment by chmarti** [comment]
One month after my comment, and this is still "Closed" and everyone is ignoring the problem... Meanwhile I've built an infrastructure on top of Azure Functions and can't deploy any changes because of this error message.

**Comment by kashimiz** [comment]
I'm very sorry for the delay, @chmarti. Can you provide us with more information about your scenario? Specifically, where you're trying to deploy to (App Service? Elsewhere?), and what deployment method version of Functions you're using.

Going forward, there are several [deployment technologies for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies) you can use as an alternative to Visual Studio's Web Deploy.

Reopening this as an ongoing issue.

**Comment by chmarti** [comment]
I was deploying a stopped C# Function App which is on a queue trigger. I am using the Publish functionality in VS.
VS Version: 15.9.18
Azure Functions and Web Jobs Tools - 15.9.03024.0

Target Framework is netcoreapp2.2
Deployment Mode is Framework Dependent
Remove additional files at destination is checked.
AzureFunctionsVersion in the csproj is v2

Here is the actual publish profile with a few private lines removed...
<?xml version="1.0" encoding="utf-8"?>

<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <UserName>REMOVED</UserName>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <PublishProvider>AzureWebSite</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>REMOVED</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>False</LaunchSiteAfterPublish>
    <ResourceId>REMOVED</ResourceId>
    <_SavePWD>True</_SavePWD>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <MSDeployServiceURL>REMOVED</MSDeployServiceURL>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <SkipExtraFilesOnServer>False</SkipExtraFilesOnServer>
    <EnableMsDeployAppOffline>False</EnableMsDeployAppOffline>
    <EnableMSDeployBackup>True</EnableMSDeployBackup>
    <DeployIisAppPath>REMOVED</DeployIisAppPath>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <SelfContained>false</SelfContained>
    <_IsPortable>true</_IsPortable>
  </PropertyGroup>
</Project>

**Comment by sanghamanvir13** [comment]
Any update on this issue? I also face this issue intermittently even if i have stopped my function app and deploy it ( both operations using Azzure DevOps Release Pipeline Tasks)

**Comment by kiran290** [comment]
Hi Manvir,

I didn't get any solution for this.

**Comment by advallu-warren** [comment]
Possible Solution, delete source of the error or the "file_name.dll" on your directory and republish it again.

**Comment by emaborsa** [comment]
Had the same problem, `<EnableMSDeployAppOffline>true</EnableMSDeployAppOffline>` did not help. 
Recycling the pool helped.

**Comment by XA007** [comment]
Just restart the resource on Azure Portal.

**Comment by Mizuwokiru** [comment]
If you have an access to IIS Server machine, try to stop website and kill **w3wp.exe** process related to it.

**Comment by MCaetanoPJ** [comment]
I got resolve this problem changing the configuration: "Release" to "Debug" in screen "Publish Web" and publishing again.

**Comment by Yush0** [comment]
I was able to reproduce this behaviour by running a request that contains only await Task.Delay(40000); during deployment.

**Comment by alandraper** [comment]
I have the same problem regularly.  I already have the EnableMSDeployAppOffline set. Publish usually works on the 2nd attempt.

**Comment by Cokoi-28** [comment]
Recycle pool on your Host

**Comment by zaksim** [comment]
I don't know why we are still having this problem when using dotnet with the IIS.
We are still controlling IIS via command to recycle or stop the application pool in CI to publish our app.
For now, msbuild is triggered by dotnet publish and the operator has no option to wait for stop using .dll file after the app_offline file was published.
