### ISSUE TITLE
 Unable to run Eventhub trigger -Java-Microsoft.Azure.WebJobs.EventHubs: Value cannot be null -

### ISSUE THREAD

**Issue by panneerpst** [Azure/Azure-Functions#1156]
I am trying to create a simple event hub trigger using the steps mentioned in the azure portal.

1)mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DappName=mylearningfuncapp-tac -DappRegion={region} -DresourceGroup={resourceGroup} -DgroupId=com.mylearning.group -DartifactId={functionAppName}-functions -Dpackage=com.{functionAppName} -DinteractiveMode=falsemvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DappName=mylearningfuncapp-tac -DappRegion={region} -DresourceGroup={resourceGroup} -DgroupId=com.mylearning.group -DartifactId={functionAppName}-functions -Dpackage=com.{functionAppName} -DinteractiveMode=false
2)mvn azure-functions:add
3)EventHubTrigger
4)Mvn clean package
5)mvn azure-functions:run
While running step 5 to run the azure functions locally, the eventhub trigger is giving error 

[18-03-2019 06:38:56] Error indexing method 'Functions.Eventhub-test-trigger-func'
**[18-03-2019 06:38:56] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.Eventhub-test-trigger-func'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null.
[18-03-2019 06:38:56] Parameter name: receiverConnectionString.**

function.json
{
  "scriptFile" : "..\\eventhubfunc-functions-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.eventhub.trigger.Eventhub_test_trigger_func.run",
  "bindings" : [ {
    "type" : "eventHubTrigger",
    "direction" : "in",
    "name" : "message",
    "connection" : "Endpoint=sb://mylearnings1.servicebus.windows.net/;SharedAccessKeyName=mylearning;SharedAccessKey=rNAIVXDfk0QVdYqyalsMmHiYV3m6hEWnOY2upbmM21I=;EntityPath=mylearningeventhub",
    "eventHubName" : "mylearningeventhub",
    "cardinality" : "MANY"
  } ]
}

**Comment by soninaren** [comment]
the configuration here is incorrect. The `function.json` should have the name of the connection string setting and the actual connections string should be in the `local.settings.json.`

**function.json**
`"connection" : "<ConnectionStringSettingName>",`

**local.settings.json** 
`"<ConnectionStringSettingName>" : "<ActualConnectionString>",`

**Comment by panneerpst** [comment]
Thanks for you valuable time Soninaren. My bad i referred to wrong property, i have corrected and it worked. I forget to update you on the same. 

Do you have any reference document to configure connection values from KeyVault?

**Comment by soninaren** [comment]
There is some documentation for key vault integration here.
https://azure.microsoft.com/en-us/blog/simplifying-security-for-serverless-and-web-apps-with-azure-functions-and-app-service/

**Comment by VallabhL** [comment]
> the configuration here is incorrect. The `function.json` should have the name of the connection string setting and the actual connections string should be in the `local.settings.json.`
> 
> **function.json**
> `"connection" : "<ConnectionStringSettingName>",`
> 
> **local.settings.json**
> `"<ConnectionStringSettingName>" : "<ActualConnectionString>",`

I have correct configuration and I am still getting that error. Here is my function.json:
{
  "scriptFile" : "../azure-functions-archetype-0.0.1-SNAPSHOT.jar",
  "entryPoint" : "com.realtime.azure.functions.Function.eventHubProcessor",
  "bindings" : [ {
    "type" : "eventHubTrigger",
    "direction" : "in",
    "name" : "msg",
    "connection" : "connectionURL",
    "eventHubName" : "rteventhub",
    "cardinality" : "MANY"
  } ]
}
and heres is my localsettings.json:
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "java",   "connectionURL":"Endpoint=sb://rteventhubtemp.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YISrGFP9FozWULLHdiZLR7RzOnCRAv0q06Zq9kRcz8U="
  }
}

**Comment by VallabhL** [comment]
> Thanks for you valuable time Soninaren. My bad i referred to wrong property, i have corrected and it worked. I forget to update you on the same.
> 
> Do you have any reference document to configure connection values from KeyVault?

@panneerpst  Can you help me solve this issue?
