### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by gabrielbaptista** [Azure/Azure-Functions#2015]
I am currently using the latest Visual Studio 2022 Preview.

Just created a new Function App sample with a TimerTrigger Function. 

As soon as I run the code, I got the error.

![image](https://user-images.githubusercontent.com/4146065/129489853-bcaafbdf-9eac-4f53-927d-8eac5a201b5c.png)

**Comment by sujayvsarma** [comment]
I have the same issue. Here is my .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.7.2-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

**Comment by sujayvsarma** [comment]
I have the same issue. Here is my .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.7.2-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

**Comment by v-bbalaiagar** [comment]
Hi @gabrielbaptista / @sujayvsarma , Triaging this issue as it requires investigation.

**Comment by BikeInventor** [comment]
Hi, having the same issue. That's what I figured so far:

At the moment, the latest version of VS2022 is 17.0.0 Preview 3.0 which when installed, also installs .NET SDK 6.0.100-preview7:

![image](https://user-images.githubusercontent.com/11947701/129613298-d04f056c-a02a-4edb-ad8a-ad74fd8657a4.png)

In the .csproj file of the Azure Function project, we specify just 'net6.0'. I assume it means that we're effectively targeting the latest .NET 6.0 runtime installed at the machine.

![image](https://user-images.githubusercontent.com/11947701/129613635-6be2647d-2a2d-4b52-875c-6b8ec3fb2b56.png)

Therefore, after installing the 3rd preview of VS2022 you're implicitly using preview 7 which has the new String Interpolation mechanism described [here](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/).  That's where the 'DefaultInterpolatedStringHandler' comes from.

It would not be a problem should the Azure Functions Core Tools 4 would work the same way (i.e. just use the latest runtime installed) but that's not how it works. Instead of using the preview-7 runtime located here:

%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19

Azure Functions Core Tools 4 uses its own runtime files located here:

%USERPROFILE%\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin

which in my case appear to be preview-5 which obviously doesn't have the new Interpolation feature, hence the error.

![image](https://user-images.githubusercontent.com/11947701/129615277-54aa4e26-49e7-4b62-8330-029a0ae41075.png)


So, that's what you can do as a temporary workaround:
1. Go to the %USERPROFILE%\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin folder. 
2. Back up the 'bin' folder just in case.
3. Replace the files in that folder with the files from %PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19 folder.

**Comment by sujayvsarma** [comment]
@BikeInventor  - Replacing the files will not help after publishing to Azure unless you're planning on self-hosting with the custom runtime setup as above ?

**Comment by AdamCoulterOz** [comment]
I just went and built the function core tools myself from the release_4.0 branch:

https://github.com/Azure/azure-functions-core-tools/tree/release_4.0

**Comment by BikeInventor** [comment]
> @BikeInventor -
> 
> The file replacement in the Bin folder confirms the incorrect .Net Runtime files used between the project and Azure Functions runtimes. But, it wont help once you deploy to Azure unless you are deploying in self-hosting mode ?

@sujayvsarma 

I don't have any issues with deploying & running my function in Azure because the CI/CD pipeline builds it with the latest (preview-7) SDK which is also installed on the AF host. 

![image](https://user-images.githubusercontent.com/11947701/129864680-8626d84d-ffe6-4840-b57f-b39cc7c1cab7.png)

**Comment by GeordieStew** [comment]
Any fix in sight for this?

**Comment by philcarbone** [comment]
I've replaced any files in here:
`%USERPROFILE%\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin`

That were from here:
`%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19`

But I still get this error. I've tried killing the node.exe process, restarting VS, restarting my computer, etc. I can't get it to work still.
Thoughts?

**Comment by philcarbone** [comment]
I figured it out. I needed to replace the files in:
`%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\4.3.0\cli_x64`

with the files in here:
`%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19`

**Comment by iaingymware** [comment]
> I figured it out. I needed to replace the files in:
> `%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\4.3.0\cli_x64`
> 
> with the files in here:
> `%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19`

Thanks, I've been trying to fix this issue for a couple of days.  For me it was particularly when trying to execute an EFCore query.  

This has resolved the issue.

**Comment by v-bbalaiagar** [comment]
Let us know if the above information resolves your query, or if you have any further queries.

**Comment by sujayvsarma** [comment]
@v-bbalaiagar - The above is not a "fix". It is a temporary workaround. When we deploy such an application to the Cloud, it won't work unless you publish it in "self-contained" mode. 

We need a proper fix for this from the Azure Functions engineering team.

**Comment by GeordieStew** [comment]
As far as I know, mine seems to work in Azure. But not locally.

> @v-bbalaiagar - The above is not a "fix". It is a temporary workaround. When we deploy such an application to the Cloud, it won't work unless you publish it in "self-contained" mode.
> 
> We need a proper fix for this from the Azure Functions engineering team.

**Comment by v-bbalaiagar** [comment]
Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Tagging @anthonychu / @brettsam, for further investigation

**Comment by brettsam** [comment]
Is anyone still reproducing this with .NET 6.0 RC1 and the latest core tools (https://www.npmjs.com/package/azure-functions-core-tools/v/4.0.3780). .NET 6.0 previews include breaking changes and this has conflicted with the core tools releases for some periods of time. Right now, everything should be caught up and things should work smoothly... but please let us know if that is not the case.

**Comment by junalmeida** [comment]
I'm having this same problem with `.NET 6.0.100`

**Comment by brettsam** [comment]
@junalmeida -- can you share your sample csproj? Are you using the latest packages for everything?

**Comment by rgbetanco** [comment]
I am getting the same issue when trying to add identity framework. First i added the package like so
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
then i use this command
dotnet-aspnet-codegenerator identity -dc NombreDelProyecto.Data.DataContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation" --useSqlite
and i got the following error
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.Execute(String[] args, ConsoleLogger logger)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.Main(String[] args)

**Comment by brettsam** [comment]
@rgbetanco -- can you also share your csproj? Are you using the latest Microsoft.NET.Sdk.Functions package?

**Comment by rgbetanco** [comment]
@brettsam 
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.1-dev-00229" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.1-dev-00947" />
  </ItemGroup>

</Project>

**Comment by rgbetanco** [comment]
@brettsam 
I updated all my referenced packages like the following
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.1-dev-00229" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.1-dev-00947" />
  </ItemGroup>

</Project>
```
I also decided to try adding Identity without the code generator, now the error is as followed:
``` bash
➜  NombreDelProyecto git:(master) ✗ dotnet ef migrations add IdentityMigrations
Build started...
Build succeeded.
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.TypeInitializationException: The type initializer for 'System.SharedTypeExtensions' threw an exception.
 ---> System.TypeLoadException: Could not load type 'System.DateOnly' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   --- End of inner exception stack trace ---
   at System.SharedTypeExtensions.ProcessType(StringBuilder builder, Type type, Boolean fullName, Boolean compilable)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The type initializer for 'System.SharedTypeExtensions' threw an exception.
```

**Comment by brettsam** [comment]
@rgbetanco -- your project doesn't appear to be using Azure Functions, which is what this repo is for. You may want to take your issue to another repo -- maybe the EF repo? https://github.com/dotnet/efcore/issues

**Comment by rgbetanco** [comment]
@brettsam ok, thanks

**Comment by Boditha** [comment]
I'm having the same issue with running a timer triggered Azure Function in Azure. It doesn't complain when I run the same locally. 

Built using Visual Studio 2022 17.0, .NET 6.0, Azure Function V4

**Comment by brettsam** [comment]
@bodisov -- can you share your csproj file? I'm specifically interested if you're up on the latest of all the Functions-related packages.

**Comment by ddobric** [comment]
I had the same issue when creating the function project from the default template.
For example:
~~~
 func init . --docker
~~~

This creates a new function, that's starts but when triggered (in my case TimeTrigger) fails with:

> 
Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

I have downloaded the project file to net5.0 and referenced the following packages:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.30" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```
After this, all works fine.

### Recap
I have every year the same issue. New .NET or VS comes out with mostly new function runtime. Result: It does not work.
I would like to encourage the team to pay more attention in the future. This is always the issue since the beginning of the function runtime. I'm not saying that we every year have exactly the exception. But when the VS comes out, the last thing I will ever try is the new function runtime.

**Comment by phil-w** [comment]
My own issue with this was solved by the details in here leading me to my own problem. I had a global install of azure-functions-core-tools in %USERPROFILE%\AppData\Local\AzureFunctionsTools which of course I need to update at the same time as updating .Net Core and the Azure Functions boiler plate.

I just used npm to update that sucker to v4 and that error went away. 
Now I just have to slot the old code into the new boiler plate... and hope Azure actually supports 6.0/4.0 in live...

**Comment by xairrick** [comment]
As suggested by @BikeInventor replacing the files in 
`%USERPROFILE%\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin`
with the files from 
` %PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App`
resolved the 'Could not load file or assembly' error I was getting when running from Visual Studio

**Comment by colindeclue** [comment]
I am still having this issue, as well, when running locally. I have not yet deployed it up to Azure.

Here is my csproj file:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by colindeclue** [comment]
When this same app is pushed up to azure via `func azure functionapp publish ...`, it runs successfully using string interpolation. So the issue is only when running locally.

**Comment by Rashair** [comment]
@phil-w solution worked for me - for anyone wondering, for update / install you need to run:
```
npm install -g azure-functions-core-tools@4
```
for the version - it's not mentioned anywhere in the Readme yet.

**Comment by rasert** [comment]
> I am having this issue when running in Azure. Locally it is working flawlessly. Here is my csproj:

I found out that the reason my function was failing in Azure is that the AzureFunctionsVersion in my project was 4 but in Azure it was v3. So I downgraded my function from net6.0 to netcoreapp3.1 and AzureFunctionsVersion v3.
