### ISSUE TITLE
EventHub-Triggered Functions with non-default consumer group not being triggered when Function App idles out 

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#230]
EventHub-Triggered Functions that use non-default consumer group works fine when Function App is opened in Azure Functions Portal or the Function App process has not idled out.

After the Function App process has idled out, the Function will not be triggered when new events are detected.

**Comment by tohling** [comment]
This issue is being fixed as of 03/29/2017 and will be rolled out in the next deployment. ETA is 3rd to 4th week of April 2017.  I will update this thread when fix is fully rolled out in production.

**Comment by hari2github** [comment]
Is this issue applicable only in Consumption Model or in App Service model as well?

**Comment by tohling** [comment]
This is only applicable to the Consumption Model.

**Comment by tohling** [comment]
Sorry, but this fix is delayed unexpectedly and will be on the next deployment train.  ETA is targeted to be mid-May.  I will update this thread again when the fix is rolled out.

**Comment by tohling** [comment]
Bug is fixed and currently in production.

**Comment by cliffyq** [comment]
I have a event triggered function using non-default consumer group and consumption plan, it still goes idle every once a while and I have to restart the function to let it pick up new events, looks like this bug is not fixed

**Comment by PKaur1** [comment]
I am still facing this issue with my function which is using non-default consumer group and is running on consumption plan. Is there any update?

**Comment by kashimiz** [comment]
I'm sorry you're still encountering issues with this, @PKaur1. Could you open a new issue about this and link to this one? Comments on closed issues are often missed by the team; I only noticed yours because of a chance Google search about another topic.
