### ISSUE TITLE
Every folder containing function.json  in $(OutDir) deleted after build

### ISSUE THREAD

**Issue by rawlukMike** [Azure/Azure-Functions#319]
Using Postbuild target I copy some Python Function to $OutDir after build.
`
<Target Name="PostBuild" AfterTargets="PostBuildEvent"><Copy SourceFiles="PythonWebRequest\function.json" DestinationFiles="$(OutDir)PythonWebRequest\function.JSON">
</Copy>
</Target>
`

However you do some cleanup that removes folders containing function.json file that was not created through build action, which removes my Python code (not supported in visual studio).

If I copy this folder manually after running emulated functions it is picked up and works properly.

Is there any way to add Python function to visual studio solution right now?
That approach would work for me if not for manual cleanup.

**Comment by lindydonna** [comment]
What version of the build package are you using?  We've recently released alpha5 which should fix this bug: https://github.com/Azure/azure-functions-vs-build-sdk/releases/tag/1.0.0-alpha5

**Comment by rawlukMike** [comment]
I have updated to alpha5 yet the problem is still there. There is some after build cleanup that deletes every folder containing function.json that was not created during build.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#53
