### ISSUE TITLE
Function goes idle when running in Consumption Plan with Service Bus Queue trigger

### ISSUE THREAD

**Issue by vyjayanthiraja** [Azure/Azure-Functions#370]
I have a function app containing two functions and the app is deployed in the Consumption Plan. Both functions are triggered by two different service bus queues, one for each function. However, I notice that the functions appear to be idle and don't process the service bus queue messages as soon as they come in. I need to browse to the function on the portal and it is only at that point that the function seems to "wake up" and process all the messages off the queue.  #229 seems to be a related issue, however I am not doing anything with dead letter queues so I wouldn't expect that to apply here.
Are there any other known issues that could be causing this? With the consumption plan, I would expect that the functions trigger each time a message enters the service bus queue and don't need to be manually poked for the processing to happen.
Would be happy to provide more info to help the investigation, just let me know what you need!

**Comment by tohling** [comment]
@vyjayanthiraja, is the Service Bus connection string for the Function in question assigned only Listen rights?  If yes, to mitigate, kindly use a connection string that has Manage rights.  There is a regression that is fixed but not yet rolled out to production. 

We are tracking the fix [here](https://github.com/Azure/azure-webjobs-sdk-script/issues/1048#issuecomment-310538965).

**Comment by vyjayanthiraja** [comment]
No it has Manage rights, in fact I just updated to use the RootManageSharedKeyAccess connection string but still seeing the idle behaviour.

**Comment by tohling** [comment]
I will need the following information to investigate further:

1. When the Function executes as expected in the Portal, you should be able to see the "Function completed..." entry in your logs.  Could you provide something similar to the following?

 `2017-06-27T08:11:51.359 Function completed (Success, Id=abcdefg-69f8-4374-ad58-905645418a00, Duration=2770ms)  
`

2. The region your Function App is allocated in.

**Comment by vyjayanthiraja** [comment]
@tohling thanks a lot for the quick responses! Here is the information:
1. Are these the logs you are talking about or something else?
![image](https://user-images.githubusercontent.com/6101620/27772372-af289486-5f15-11e7-9a17-963227e23cd1.png)
I can't find the specific line you referenced so I'm hoping this is equivalent. Here's the context id in that image : 184fb268-b395-49fb-bf00-1aeaee8ddeef
2. My Function App is in East US 2

**Comment by tohling** [comment]
In the Functions Portal, browse to your Function code, e.g. run.csx, or index.js file.  At the bottom on the UI, click on the "Logs" button to launch the log view.  If there are new events entering your Service Bus, your Function should trigger and execute your code.  The log view should show "Function started..." followed by a corresponding "Function completed..." entries.  If your Service Bus is not very busy, you may have to wait till a new event enters the Service Bus for your Function to trigger.

**Comment by vyjayanthiraja** [comment]
Alright I triggered one of my functions and here is the log line 
2017-07-02T18:22:08.479 Function completed (Success, Id=4fd1c5c1-597e-461c-a1d0-5e8ce692ae6e, Duration=11ms)
Let me know if you need anything else!

**Comment by tohling** [comment]
Thanks!  I am not too familiar with the monitoring page snapshot that you posted earlier, but the context id would have worked as well.  I am investigating and will update this thread soon.

**Comment by tohling** [comment]
Looking at the function.json configuration for both your ServiceBus Functions (A****Processor and N****Processor), I noticed that the entry for the connection string is set as

`"connection":"serviceBusConnection"`

In your Function App's app settings, I could find only the setting with the key `AzureWebJobsserviceBusConnection`.  Could you try **one** of the following?

1. Modify the key `AzureWebJobsserviceBusConnection `to `serviceBusConnection`, or 
2. Create a new app setting with the key `serviceBusConnection  `and assign the connection string with Manage rights.

Doing either 1 or 2 should fix it.  Update this thread when you have done so, and I can check our internal logs as well to confirm if your Functions are setup correctly in Consumption plan.

**Comment by vyjayanthiraja** [comment]
@tohling thanks a lot for the quick update, option 2 worked for me! I do have a couple of follow up questions though:
1. When I initially deployed the functions with just the key "serviceBusConnection", I received an error message stating that the "AzureWebJobsserviceBusConnection" was missing. So I renamed it to "AzureWebJobsserviceBusConnection". But, as you rightly pointed out, this causes my function to not be triggered when a message arrives in the queue. So I now have two keys, one named "serviceBusConnection" and another named "AzureWebJobsserviceBusConnection". Why are two required?
2. (out of interest) Why did the missing key manifest in the idle function behaviour?

**Comment by tohling** [comment]
@vyjayanthiraja, glad to hear that your Function is working as expected now.  

**Answer 1.** It is possible that the pipeline that does not rely on the central listener accepts a connection string of the format `AzureWebJobs{connectionStrinKeyName}`.  I checked our [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus) and the only comment I could find related to this was  the following,

"If you leave connection empty, the trigger assumes that a default Service Bus connection string is specified in an app setting named `AzureWebJobsServiceBus`."

What happens when you remove `AzureWebJobsserviceBusConnection`?  If you still see the error, please file a separate issue and we will investigate.

Answer 2.  To answer this question, let's go over the following background information.

### Background
A Function App instance is a process instance for all Functions inside the Function App. For a Function to execute, at least 1 Function App instance must be running.

In Consumption Plan, a Function App instance is launched due to one of the following scenarios:

1.  **Function App is being accessed via Azure Portal -** The UX workflow loads the Function App on behalf of the user, effectively forcing the Function App to be launched and start executing any Functions that are triggered.

2.  **Function App instance is launched by central listener service -** There is currently a central listener service that acts as the proxy listener for events on all triggers. It is responsible for 

    - listening for new events, 
    - launching a Function App instance if no-active instances exists, and 
    - scaling new instances when necessary.
 
For Functions that are created under the Consumption Plan, the Function App instance will stay alive for 5 minutes (or 10  minutes if configured as such). After 5 minutes, the Function App instance will idle out. Once the **last** Function App instance idles out, if **Scenario #1** does not occur, then the Function will only be triggered by new events arriving in **Scenario #2**.

### Issue

After you have close the Portal, your Function App eventually idles out and ceases to exist.  Your Function will only be triggered by the Scenario #2 mentioned above.  Because the central listener was could not resolve the value for `serviceBusConnection`, its "listen for events" code-path for your Function kept failing and was unable to launch an instance of your Function App when new events arrived for that Service Bus.

**Comment by vyjayanthiraja** [comment]
@tohling thanks so much for the detailed explanations, those are really helpful! I went ahead and deleted the AzureWebJobsserviceBusConnection string and it still works. I guess the error occurred back when I didn't have any app settings (including serviceBusConnection) specified. I will go ahead and close this issue now, thanks for the quick resolution!

**Comment by ravibutola1982** [comment]
for us its still going in idle state even we have 0 */1 * * * * one minute timer , usually it goes after business hours CST(5:30 PM), seem no one logging at that time to azure portal function app.

please suggest what to do?

**Comment by lindydonna** [comment]
@ravibutola1982 That sounds like a different issue. 
For this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply. Please include your configuration in your question.

**Comment by pseabury** [comment]
So if we specify our servicebus connection via some other key in the function like 

`public static void ProcessQueue([ServiceBusTrigger("myqueue", AccessRights.Listen, Connection = "MyServiceBusConnectionString")], ...)`

Then the central listener that relies on "serviceBusConnection" or "AzureWebJobsServiceBus" (which one, and why two?) being in the config will fail to wake the service after it idles out?  Or in other words, we have to use one of those two keys in our config to specify the serviceBus connection so that the listener can wake up our functions app, but we can specify whatever connection info we want if we assume that the functions app is alive?  

Thanks!

**Comment by brankygrad** [comment]
Setting 'serviceBusConnect' in our function configuration has not prevented our function from going idle after an indeterminate period of time.
The (sanitized) setting json is as follows:
```
{
  "ConnectionStrings": {
    "MyConnectionString": "Server=tcp:project.database.windows.net,1433;Database=myDB;User ID=user@project;Password=password;Encrypt=True;Connection Timeout=30;"
  },
  "Values": {
    "serviceBusConnection": "Endpoint=sb://project.servicebus.windows.net/;SharedAccessKeyName=SharedAccessKeyName;SharedAccessKey=KEY_HERE",
  }
}
```
and the function signature is: 
`public static void ProcessQueue([ServiceBusTrigger("queueName", AccessRights.Listen, Connection = "serviceBusConnection")] ...)`

Should we also have an 'AzureWebJobServiceBus' setting? Can anyone clarify the difference between how those two settings are used or notice anything else with the settings that might be causing the function to not properly be triggered after a period of inactivity?

Thank you.
