### ISSUE TITLE
Cannot debug Azure Function from Cloud Explorer

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#393]
_From @bc3tech on July 12, 2017 20:34_

Filing issue per direction [here](https://social.msdn.microsoft.com/Forums/expression/en-US/ead896df-75d0-4a4f-abec-6ff5892e9b9c/remote-debugging-azure-functions-with-vs2017-preview-3-and-latest-azure-function-tools?forum=AzureFunctions&prof=required) and despite instructions shown [here](https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/).

1. open azure portal
1. create new azure function (c#)
1. Open Visual Studio 2017 Preview 15.3.0
1. Ensure Azure Function Tools v0.2 (latest) installed
1. Open Cloud Explorer & find Function created in portal
1. Right click the function.
1. Observe no 'Attach debugger' option is available:
![image](https://user-images.githubusercontent.com/1967433/28138713-9d18b016-6706-11e7-8b6e-8706dfcf6311.png)

_Copied from original issue: Azure/azure-webjobs-sdk-script#1672_

**Comment by lindydonna** [comment]
_From @tohling on July 12, 2017 21:59_

@bc3tech , this is a currently a known issue.  It is being actively investigated and fixed by the VS team that owns Cloud Explorer.  

To unblock yourself immediately, we suggest that you try to an older workflow that may involve a few extra steps but should work.  Here are the steps:

1.  From the Portal, under the **Overview** tab, 
     a. Download the publish profile for your Function App.  Open the downloaded file and in its content, look for the credentials,
               i. userName
               ii. userPWD

      b.  Copy the URL to your Function App

2.	From the Portal, under **Application settings**, 
        a.  Turn on Remote Debugging
        b.  Select Remote Visual Studio Version as 2017

3.	From VS 2017 in the list of menu items, select **Debug->Attach To Process**

4.	In the **Connection Target:** text area, copy and paste the URL obtained from 1b followed by **:4022** as that is the port for the remote debugger for VS2017, e.g.  `myFunctionSite.azurewebsites.net:4022`

5.	You will be prompted for your credentials.  Type in the username and password that you obtained from **1ai** and **1aii**.  **NOTE:** For username it is preceded by **`.\`**  For instance if your username is **`$myusername`**, key-in **`.\$myusername`**

6.	You should now see a list of processes that you can attach to.  Select the one that has the process name **w3wp.exe** and click on the **Attach** button.

**Comment by lindydonna** [comment]
@bc3tech This should be fixed soon with an in-place update to Cloud Explorer. I'll update this thread when the fix is out. Thanks for your patience.

**Comment by ToddBooth** [comment]
It didn't work for me.  The problem was 4) I could not connect to my function.  I get a "Found 0 connections".  Note I ran nmap.org (nping) and verified that I can make a tcp connection to my function:4022.  So there is something listening.
Could anyone help me and try connecting to my function.

When you try connecting to my own function, do you a "Found 0 connections" or are you prompted for the userid/pw?

The attach to process connection target to my function is: 
function2454.azurewebsites.net:4022

I assume in 4: I should use Connection Type Default.

Thanks so much!  Todd

**Comment by tohling** [comment]
@ToddBooth, thanks for the clarification.  So, did these instructions work for you?

**Comment by ToddBooth** [comment]
@tohling   Yes, now everything is working for me.  This is a really incredible feature, which is extremely helpful.

**Comment by doronguttman** [comment]
I have followed the instructions by @lindydonna but getting:

> Visual Studio was unable to create a secure connection to ****.azurewebsites.net:4022. Authentication failed.

It is asking for credentials again.

**Comment by lindydonna** [comment]
@tohling Do you have any workarounds for @doronguttman?

**Comment by melzoghbi** [comment]
I am getting the same error message as in @doronguttman? using VS2017 or VS2017 Preview. any workaround? the IDE shows Remote (no authentication) option and there are no way to set username/password. also default option shows the same error authentication failed error!

![image](https://user-images.githubusercontent.com/11993393/29891588-a09ce0e0-8d99-11e7-8e1a-fd356018f9e2.png)

![image](https://user-images.githubusercontent.com/11993393/29891700-039ed3e2-8d9a-11e7-9834-9bad86cfa27a.png)

Any thoughts?

**Comment by cwilli34** [comment]
I am having this same issue, but I cannot connect with server explorer or manually attaching to a process under the "Debug" menu.  I can't connect to a Azure webapp at all.

**Comment by aashishtripathi** [comment]
I am also having the same issue and not able to find any connections to login.  Any help on this would be appreciated.

**Comment by tracy-zaact** [comment]
I am having a similar issue.  I have VS 2017 15.3 Pro installed, but the Cloud and Server Explorer do not 'see' my Function App Service.  When I try the manual workflow indicated above for debugging, it does not prompt me for credentials at all, but finds zero connections and then gives me the error indicated below.  I have also provided a screen shot of my general application settings below.  

I am currently on a trial Azure subscription.  

![ss1](https://user-images.githubusercontent.com/25020454/30177031-4868dea8-93b9-11e7-9c87-b270c8ac0ba8.png)

![ss1](https://user-images.githubusercontent.com/25020454/30178013-6e7f769e-93bc-11e7-9561-22495162481f.png)

**Comment by justcla** [comment]
@tracy-zaact This error message is presented when then website you are trying to connect to does not exist. Did you make a typo when entering the website URL?

The simplest way to get around this is to log in to the Cloud Explorer with the account that has the correct subscription. Then you should see a list of valid websites associated with that subscription and when you choose one, it will appear in the Cloud Explorer. You can then right-click the website and choose "Attach Debugger".

Here's an example:
![image](https://user-images.githubusercontent.com/17131343/30188469-5b312228-93e3-11e7-819f-0e0bdd65844a.png)

**Comment by tracy-zaact** [comment]
Thanks @justcla - I am currently logged into VS with the relevant account (see below), but for some reason my Cloud Explorer does not get populated with the contents I see in Azure Portal.  Is there a separate authentication process for the Cloud Explorer?  I have tried uninstalling and reinstalling the Cloud Explorer with the same results, and I also tried it in VS 2015 with the Azure Web Tools installed and got the same result.  

One point of note is that this is a different O365 account than I am currently logged into my desktop with, but my guess is that should not matter.  

![ss1](https://user-images.githubusercontent.com/25020454/30188589-ffe13c86-93e3-11e7-8b01-7d13cafdb645.png)

**Comment by justcla** [comment]
Yes, there is a separate "authentication" process for Cloud Explorer.
You need to tell the Cloud Explorer which accounts to display.
To do this, click the little "person" icon at the top and it will offer you a choice of all your signed in accounts.
Tick the boxes to select which ones you want to show.
![image](https://user-images.githubusercontent.com/17131343/30188791-4f0b26cc-93e5-11e7-981e-1ddb7e1e86d3.png)

You can click "Manage Accouts" to add accounts that aren't appearing.

**Comment by tracy-zaact** [comment]
@justcla Eureka!  👍

**Comment by melzoghbi** [comment]
After the recent functions runtime 1.0.2 and VS2017 preview updates! things started to work with no authentication problems.

**Comment by NichUK** [comment]
I'm not sure if this is a linked issue (I think probably one for the Cloud Explorer team), but until a moment ago, I was still having problems attaching a debugger to my function app through Cloud Explorer, but then I noticed that the function app had the wrong icon next to it - a lightbulb.
It turns out, that I had Application Insights (for my Azure Functions App) named the same as the functions app, and the Application Insights was *hiding* the Functions App in Cloud Explorer. I deleted the Application Insights, and suddenly my Azure Functions app reappeared in Cloud Explorer, complete with Attach Debugger link.

**Comment by SharePointSean** [comment]
I've tried everything I've read here and other places. Removing Application Insights helped to see the function app in Cloud Explorer. However, no matter what credentials I use (including those from the profile settings), I cannot get authenticated. Putting .\ in front of the userName resolves to the local machine\theusername. I'm so close. Anyone else have anymore thoughts? Same thing happens whether cloud explorer of the debug\attach to process.

**Comment by kevinmcfarlane** [comment]
I too have no Attach Debugger option. This is with VS 2017 15.4.4.

A thread I read elsewhere reported that a user could see it in one revision and then it disappeared in the next. This may have been 15.3.2 ->15.3.3.

Elsewhere someone said it's now in Sever Explorer, not Cloud Explorer, but I still don't see it.

**Comment by darrengillis** [comment]
I got it working once from the server explorer and then now can't get it working at all - with the following: 
![image](https://user-images.githubusercontent.com/1687455/33468082-9213bb1c-d627-11e7-8622-911c7c93e1cb.png)

Also tried following the workaround from way back in July and had no luck.  

I've seen the remote debugging feature working in demos, videos, etc. and yet have not had any success with it so far.  When I first saw it, it seemed like a feature that was too good to be true... and what does that usually lead to...

**Comment by Robzilla** [comment]
Using the server explorer I can bring up the attach debugger but simply can't authenticate. When I use the credentials from the publish profile it thinks the account is a local domain joined account. If I use the .\$myusername notation described above Studio tries to authenticate against my local machine, not the remote server. So bloody frustrating. This is one of the big advantages Azure has over AWS. Please make this work. Currently running Studio 15.4.5

**Comment by donamk** [comment]
Same here. I followed everything in this thread, there is no attach debugger menu in the cloud explorer popup menu.

**Comment by Robzilla** [comment]
Hi donamk, try using the server explorer. I couldn't get the cloud explorer to work but at least the server explorer found the process to attach to. If only I could authenticate :-(

**Comment by khalid-halo** [comment]
Getting similar issue, Unable to connect to Microsoft Visual Studio Remote Debugger name ''. The connection was terminated

**Comment by azachert** [comment]
Same here

**Comment by ds27680** [comment]
Same problem here. I have the menu but get asked about the credentials. I used .\$username and the pwd from the publish profile. No luck...

Not to mention that I started out with the menu missing altogether, now after installing the 17.5 update I have it but I cannot get by the authentication.

I even checked this:

We had some customer reported same issue before. It turned out to related to customer's client machine settings.

Remote debugging uses NTLM V2 authentication. Can you try this?

On your PC, open secpol.msc, locate to local policies—security policy

Double click: network security: Lan manager authentication level, select “send NTLMv2 response only”, click Apply and OK.

see https://social.msdn.microsoft.com/Forums/en-US/ffc5eade-024a-4598-a707-6837d72a894b/unable-to-remote-debug-my-website-from-vs2013-authentication-error?forum=windowsazurewebsitespreview

**Comment by cateyes99** [comment]
now 9 and half months have passed, I still experience the issue that exactly @doronguttman mentioned on [Aug 24, 2017](https://github.com/Azure/Azure-Functions/issues/393#issuecomment-324394010). I'm using **VS2017 15.7.3** + the Extension **Azure Functions and Web Jobs Tools 15.0.40502.0**. This is a very useful feature, shouldn't the azure function team give us some further info/explanation regarding this? @tohling @lindydonna

**Comment by mehowq** [comment]
I seem to be able to attach to the w3wp.exe process and authenticate with the publish profile credentials using VS 2017 15.7.5 and Azure Functions and Web Jobs Tools 15.0.40608.0. However, I'm getting the 'The breakpoint will not currently be hit. No symbols have been loaded for this document' error message. Any thoughts?

**Comment by jeromekol** [comment]
@mehowq it's a known bug. They will fix it soon. When attaching make sure in the 'Attach to:' select button you pick 'Managed (CoreCLR) code.

https://github.com/Azure/Azure-Functions/issues/844#issuecomment-407128621

**Comment by mehowq** [comment]
@jeromekol OMG it worked! Thanks! @lindydonna It would be useful to include that in the instructions.

**Comment by vjsCloud** [comment]
Hi All,
I am able to attach the process with both Server Explorer and manual method. However, I get the below error when the debugger is attached
![debugerror](https://user-images.githubusercontent.com/42511228/44307464-4b1d2c80-a3a3-11e8-80c2-129db23d3332.png)

I have checked the appmanifest file and it has all the values required. However, somehow the {StandardTokens} parameter is not getting replaced with the actual values and this is the reason the breakpoint is not being hit and it throws the attached error. Please help as I have put 3-4 days now banging my head against this error.

Any help is highly appeciated

**Comment by seannybgoode** [comment]
Same here. VS 2017, can't attach the debugger either via cloud explorer, nor manually attaching to process

**Comment by gs-optimus** [comment]
>           I seem to be able to attach to the w3wp.exe process and authenticate with the publish profile credentials using VS 2017 15.7.5 and Azure Functions and Web Jobs Tools 15.0.40608.0. However, I'm getting the 'The breakpoint will not currently be hit. No symbols have been loaded for this document' error message. Any thoughts?

I'm having the same issue, is there any resolution on this? Am trying to remote debug NodeJs Azure Function

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#292

**Comment by ColbyTresness** [comment]
Reverting move, tracking here.

**Comment by ColbyTresness** [comment]
This is fixed in VS2019.

**Comment by liben-y** [comment]
This is still not working for me on Visual Studio 2019 with the latest update available as of this post. I've uninstalled and reinstalled visual studio 2019. Have tried to use the username/pwd in the publish profile file and still not working. The option to debug is not available in Server Explorer only in Cloud Explorer.
Can only see the following:
![image](https://user-images.githubusercontent.com/16204903/73284853-14308480-41ed-11ea-81d6-91151b685b69.png)

I can see attach debugger options in cloud explorer on my app, but then I get prompted with credentials and it doesn't accept anything after that.

**Comment by liben-y** [comment]
Finally got this to work. It was related to the post @ds27680 mentioned earlier.

> Remote debugging uses NTLM V2 authentication. Can you try this?
> 
> On your PC, open secpol.msc, locate to local policies—security policy
> 
> Double click: network security: Lan manager authentication level, select “send NTLMv2 response only”, click Apply and OK.
> 
> see https://social.msdn.microsoft.com/Forums/en-US/ffc5eade-024a-4598-a707-6837d72a894b/unable-to-remote-debug-my-website-from-vs2013-authentication-error?forum=windowsazurewebsitespreview

**Comment by charliechen179** [comment]
> Yes, there is a separate "authentication" process for Cloud Explorer. You need to tell the Cloud Explorer which accounts to display. To do this, click the little "person" icon at the top and it will offer you a choice of all your signed in accounts. Tick the boxes to select which ones you want to show. ![image](https://user-images.githubusercontent.com/17131343/30188791-4f0b26cc-93e5-11e7-981e-1ddb7e1e86d3.png)
> 
> You can click "Manage Accounts" to add accounts that aren't appearing.

What a UI design. How can a user realize it's clickable? Thumbs down for VS.
