### ISSUE TITLE
Referencing Azure Functions Projects from other Projects

### ISSUE THREAD

**Issue by solvingj** [Azure/Azure-Functions#445]
I created an Azure Function Project and a Unit test project to test it. My real goal is to do some integration testing.

My test project is trying to find the DLL here:
`API.Routing\bin\Release\net461\API.Routing.dll`

But it's being output here:
`API.Routing\bin\Release\net461\bin\API.Routing.dll`

I've never had this problem with a project reference before, so I'm guessing that Azure Functions projects output to a slightly special path with the extra `\bin` , is this correct?  Does this make it impossible to point a project reference at an Azure Function project?

**Comment by vijayrkn** [comment]
@solvingj - This issue is fixed in the latest version of the Functions Sdk package-  https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.2

Updating the package version in the Functions app (csproj) from 1.0.0 to 1.0.2 should fix this issue.

**Comment by jfoshee** [comment]
Thanks for posting the resolution... Seems a similar problem still exists if you are in "Folders" view in Solution Explorer and try to debug the .csproj.

More seriously, though, this issue regresses if you right-click on the project and choose _Add New Item_ -> _Azure Function_.  The reference to `Microsoft.NET.Sdk.Functions` will revert to 1.0.0 _and_ the project type GUID will change in the .sln.

**Comment by solvingj** [comment]
good note for posterity.

**Comment by vijayrkn** [comment]
@jfoshee Thanks for reporting the issue. We will take a look. Thanks!

**Comment by vijayrkn** [comment]
>More seriously, though, this issue regresses if you right-click on the project and choose Add New Item -> Azure Function. The reference to Microsoft.NET.Sdk.Functions will revert to 1.0.0 and the project type GUID will change in the .sln.

@soninaren - Can you please fix the downgrade issue in item templates.

**Comment by soninaren** [comment]
This has been fixed in item templates.

**Comment by jeremy001181** [comment]
Hey, i am still having this problem. 

I am using Azure Function 1.0, net461, and my Microsoft.NET.Sdk.Functions is on 1.0.13 which isn't reverted to 1.0.0 when I added to my unit test project as reference, which is good. But when I press `Go To Definition` on the type declared in function project it shows me the function assembly metadata from c:\src\FunctionApp2\bin\Debug\net461\bin\FunctionApp2.dll, instead of taking me to the source code of the function.

Any thoughts?
