### ISSUE TITLE
Failed to start service after installed and configured Azure Functions Runtime preview 2

### ISSUE THREAD

**Issue by regionbbs** [Azure/Azure-Functions#617]
Hi,

I installed preview 2 of Azure Functions Runtime, and configured with configuration tool, but I can't start Azure Functions Host Activation Service.

![image](https://user-images.githubusercontent.com/1799428/33692355-d9ca0ec0-db27-11e7-8cfa-d2ab843c338a.png)
 
I got error message from Event Viewer:

無法啟動服務 (Unable to start service)。System.NullReferenceException: 並未將物件參考設定為物件的執行個體。 (Object reference not set to an instance of an object)
   於 Microsoft.Functions.Runtime.Activation.Service.FunctionAppActivationManager.Start()
   於 Microsoft.Functions.Runtime.Activation.Service.FunctionsHostActivationService.OnStart(String[] args)
   於 System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

Any configuration item I missed?
Thank you.

OS: Windows 10 Creator Update, Traditional Chinese language.

**Comment by apwestgarth** [comment]
Prior to configuring your installation did you Reset using the last option in the Configuration tool?  We have had one report of a similar issue and it was resolved by resetting the installation to factory defaults using the reset option.  Then complete the configuration and you should be able to start the service.

**Comment by regionbbs** [comment]
Yes, I had used "reset to factory defaults" to restore initial configurations and configured it again, but this issue still exists. 

![image](https://user-images.githubusercontent.com/1799428/33745430-c76c60a0-dbf1-11e7-85bc-59c987274cde.png)

**Comment by jvano** [comment]
Please try reset again but before trying to reconfigure again, make sure the folder C:\Functions is deleted or renamed.

**Comment by regionbbs** [comment]
It works. Thank you.

**Comment by jvano** [comment]
I'm glad it worked. We will improve the error description for this case and get rid of the NullReferenceException.
