### ISSUE TITLE
BadRequest doesn't include Message while OK does include message

### ISSUE THREAD

**Issue by samyun** [Azure/Azure-Functions#881]
`return new BadRequestObjectResult(message);`

`return new OkObjectResult(message);`

When run on my local environment, both lines return the expected message as the body. When run on Azure, the OkObjectResult returns the expected message while the BadRequestObjectResult returns “Bad Request” as the body.

This is using the 2.0 beta runtime, with C#.

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/Azure/azure-functions-host/pull/3097 that is being deployed right now

**Comment by samyun** [comment]
@ahmelsayed Has this deployed yet? I'm still seeing this issue.

**Comment by ahmelsayed** [comment]
no not yet. Another issue was found, and they had to retake it. https://github.com/Azure/azure-functions-host/pull/3149. It's again being deployed now. I'll update here once it's done.

**Comment by ahmelsayed** [comment]
This has been deployed now.
